=== Programming-Systems-Lab/archived-memento/pervasive/hermes/src/util/psl/memento/hermes/util/constants/constants.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Suhit Gupta (Columbia University Computer Science Dept) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="constants">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="constant">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="value" type="xs:string"/>
							<xs:element name="type" type="xs:string">
								<xs:annotation>
									<xs:documentation>type represents the data type of the value for this constant:  string, int, and double are valid values for this child.</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Programming-Systems-Lab/archived-memento/pervasive/hermes/src/util/psl/memento/pervasive/hermes/util/constants/constants.xml
<?xml version="1.0" encoding="UTF-8"?>
<constants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\rob\My Documents\workspace\psl\vtd\code\server\Server\constants\constants.xsd">
	<constant>
		<name>Test</name>
		<value>What up fool</value>
		<type>string</type>
	</constant>
	<constant>
		<name>Money</name>
		<value>1000</value>
		<type>int</type>
	</constant>
</constants>
